name: Switch Node version
on: 
  pull_request:
env: 
 NODE_VERSION: '14'

jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v4
        - name : setup node
          uses: actions/setup-node@v4
          with:
            node-version: ${{env.NODE_VERSION}}
        - name: run test
          shell: bash
          run: |
            npm install
            npm test
            node -v



          


